server:
  port: 8800

spring:
  application:
    name: rabbitmq-server
  rabbitmq:
    local:
      host: 192.168.9.16
      port: 5672
      username: admin
      password: 123456
      virtualHost: /
    cloud:
      host: 101.132.45.166
      port: 5672
      username: yushen
      password: 123123
      virtualHost: /